# Generated by Django 5.1.7 on 2025-03-17 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_alumni_options_alter_post_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['name'], 'verbose_name': 'Alumni', 'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterField(
            model_name='alumni',
            name='batch',
            field=models.IntegerField(verbose_name='Batch Year'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='experience',
            field=models.TextField(verbose_name='Work Experience'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='github_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub Profile'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Profile'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='skills',
            field=models.TextField(verbose_name='Skills & Expertise'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
