# Generated by Django 5.1.7 on 2025-03-18 06:01

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_alumni_options_alter_alumni_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.alumni_profile_upload_path, verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=myapp.models.post_image_upload_path, verbose_name='Post Image'),
        ),
    ]
